version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: himanshurawlani/objectrecognition:winsupp
    deploy:
      replicas: 3
    ports:
      - "4000:4000"
networks:
  webnet:
